name: Lint, check, build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: remove lock file
        run: rm yarn.lock

      - name: install modules
        run: yarn

      - name: run lint
        run: yarn lint

      - name: run check
        run: yarn check

      - name: build app
        run: yarn build
